# Generated by Django 3.0.3 on 2020-02-15 10:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=10)),
                ('driver', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[\\u0400-\\u04FF\\s]{3,}', 'Enter the name in cyrillic alphabet')])),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(\\+380)\\(\\d{2}\\)(\\d{3})-(\\d{2})-(\\d{2})$', 'Enter the phone number in the correct format')])),
                ('order_adress', models.CharField(max_length=100)),
                ('destination_adress', models.CharField(max_length=100)),
                ('desired_time', models.DateTimeField()),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Car')),
            ],
        ),
    ]
