# Generated by Django 3.0.3 on 2020-02-15 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[\\u0400-\\u04FF\\s]{3,50}', 'Enter the name in cyrillic alphabet or enter from 3 to 50 characters')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='telephone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator('^(\\+380)\\(\\d{2}\\)(\\d{3})-(\\d{2})-(\\d{2})$', 'Enter the phone number in the correct format')]),
        ),
    ]
